[package]
name = "rust_flow_modelling"
version = "0.1.0"
authors = ["thingus <thingus@github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.2.1"
ndarray = "0.15.1"
